# Generated by Django 3.2.16 on 2022-10-26 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pastapp', '0002_doc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='doc',
        ),
    ]
