# Generated by Django 3.2.16 on 2022-10-26 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastapp', '0003_delete_doc'),
    ]

    operations = [
        migrations.CreateModel(
            name='doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='docs')),
            ],
        ),
    ]
